
name: Build & Release Lichee-Jack Utils

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build-release:
    runs-on: ubuntu-latest

    container:
      image: debian:stable
      options: --privileged

    steps:
      - name: Install base tools
        run: |
          apt-get update
          apt-get install -y \
            ca-certificates \
            git \
            curl \
            xz-utils \
            build-essential \
            devscripts \
            debhelper \
            fakeroot \
            autotools-dev \
            autoconf \
            automake \
            libtool \
            libtool-bin \
            libconfig-dev \
            pkg-config \
            pkgconf \
            golang \
            asciidoc \
            cmake \
            gcc-riscv64-linux-gnu \
            g++-riscv64-linux-gnu \
            texinfo \
            bison \
            libusbgx-dev \
            flex

      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build all packages
        run: |
          chmod +x build-all.sh
          ./build-all.sh

      - name: Create release tarball
        run: |
          chmod +x release.sh
          ./release.sh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Lichee-Jack Utils ${{ github.ref_name }}
          files: |
            out/*.deb
            .release/**/*.tar.xz

